server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: abc@123
    url: jdbc:mysql://localhost:3306/sbms/cloudapp?useSSL=false&allowPublicKeyRetrieval=true


    username: abc
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    password: pwd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: gainilaxman@gmail.com
reg-app: 
  messages:
    regMailSubject: User Registration Success
    regMailBodyTemplateFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt